-keep class android.support.v4.app.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class android.support.v7.app.** { *; }
-keep class android.support.design.widget.** {*;}
-keep interface android.support.v7.app.** { *; }
-keep class android.support.v7.widget.SearchView { *; }
